apps/ticket_agent_web/lib/ticket_agent_web/router.ex
defmodule TicketAgentWeb.Router do
  use TicketAgentWeb, :router
  # Add this
  use Coherence.Router

  pipeline :browser do
    plug(TicketAgentWeb.Plug.Timing)
    plug(:accepts, ["html", "ics"])
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
    # Add this
    plug(Coherence.Authentication.Session)
  end

  pipeline :webhook_browser do
    plug(:accepts, ["html"])
    plug(:put_secure_browser_headers)
  end

  pipeline :protected do
    plug(:accepts, ["html", "json"])
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
    # Add this
    plug(Coherence.Authentication.Session, protected: true)
  end

  pipeline :protected_api do
    plug(:accepts, ["json"])
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
    # Add this
    plug(Coherence.Authentication.Session, protected: true)
  end

  pipeline :admin_layout do
    plug(:put_layout, {TicketAgentWeb.Admin.LayoutView, :admin})
  end

  pipeline :backend_layout do
    plug(:put_layout, {TicketAgentWeb.Backend.LayoutView, :backend})
  end

  # Add this block
  scope "/" do
    pipe_through(:browser)
    coherence_routes()
  end

  # Add this block
  scope "/" do
    pipe_through(:protected)
    coherence_routes(:protected)
  end

  scope "/webhook", TicketAgentWeb do
    pipe_through(:webhook_browser)

    post("/:provider", WebhookController, :create)
  end

  scope "/", TicketAgentWeb do
    # Use the default browser stack
    pipe_through(:browser)
    resources("/about", AboutController, only: [:index, :show])
    resources("/camps", CampController, only: [:index, :show])
    resources("/charges", ChargeController, only: [:create])
    get("/event_calendar/:slug", EventCalendarController, :show, as: :event_ics)
    resources("/events", EventController, only: [:index, :show], param: "slug")
    get("/tickets/:listing_id/new", TicketController, :new, as: :new_ticket)
    resources("/tickets", TicketController)

    get("/ticket_auth/:token", TicketAuthController, :show, as: :ticket_auth)
    get("/ticket_auth", TicketAuthController, :new, as: :ticket_auth)
    post("/custom_registration", TicketAuthController, :create, as: :custom_registration)
    post("/waitlist", WaitlistController, :create, as: :waitlist)

    get("/workshops", WorkshopController, :index, as: :workshop)
    get("/classes", ClassController, :index, as: :classes)
    get("/classes/:type", ClassController, :class, as: :class_type)
    get("/class/:id", ClassController, :show, as: :class)

    get("/privacy", RootController, :privacy, as: :privacy)
    get("/terms", RootController, :terms, as: :terms)
    get("/", RootController, :index)
  end

  scope "/", TicketAgentWeb do
    pipe_through(:protected)
    resources("/orders", OrderController)
  end

  scope "/auth", TicketAgentWeb do
    pipe_through(:browser)

    get("/:provider", AuthController, :index)
    get("/:provider/callback", AuthController, :callback)
    delete("/logout", AuthController, :delete)
  end

  scope "/dashboard", TicketAgentWeb do
    pipe_through(:protected)
    get("/", DashboardController, :index)
    get("/tickets", Dashboard.TicketsController, :index, as: :dashboard_tickets)
    get("/classes", Dashboard.TicketsController, :index, as: :dashboard_classes)
    get("/order_pdf/:order_id", OrderPdfController, :show, as: :order_pdf)
  end

  scope "/concierge", TicketAgentWeb.Concierge do
    pipe_through([:protected, :ensure_concierge])
    get("/", DashboardController, :index, as: :concierge_dashboard)
    get("/single_checkin/:ticket_id", CheckinController, :show, as: :concierge_single_checkin)
    get("/listing_checkin/:listing_slug", CheckinController, :show, as: :concierge_checkin)
    resources("/checkin", CheckinController)
  end

  scope "/api", TicketAgentWeb.Api do
    pipe_through([:protected_api, :ensure_admin])
    get("/listings/:listing_slug/tickets", ListingTicketsController, :show)
  end

  scope "/admin", TicketAgentWeb.Admin do
    pipe_through([:protected, :ensure_admin, :admin_layout])
    get("/dashboard", DashboardController, :index, as: :admin_dashboard)
    get("/config", ConfigController, :index, as: :admin_config)

    resources("/classes", ClassController, as: :admin_class)
    resources("/listings", ListingController, as: :admin_event, param: "titled_slug")
    resources("/images", ImageController, as: :admin_image)
    resources("/orders", OrderController, as: :admin_order)
    resources("/teachers", TeacherController, as: :admin_teacher)
    resources("/tickets", TicketController, as: :admin_ticket)
    resources("/users", UserController, as: :admin_user)
    resources("/webhooks", WebHookController, as: :admin_webhook)

    get("/email_template/:type/:id", EmailTemplateController, :show, as: :admin_email_template)
    get("/email_template/:type", EmailTemplateController, :show, as: :admin_email_template)

    get("/", Redirect, to: "/admin/dashboard")
  end

  scope "/backend", TicketAgentWeb.Backend do
    pipe_through([:protected, :ensure_concierge, :backend_layout])
    get("/", DashboardController, :index, as: :backend_dashboard)
    resources("/classes", ClassController, as: :backend_class)
    resources("/listings", ListingController, as: :backend_event, param: "titled_slug")
    resources("/orders", OrderController, as: :backend_order)
    resources("/teachers", TeacherController, as: :backend_teacher)
    resources("/tickets", TicketController, as: :backend_ticket)
    resources("/users", UserController, as: :backend_user)
    resources("/webhooks", WebHookController, as: :backend_webhook)
  end

  def ensure_admin(conn, _params) do
    case conn.assigns.current_user.role do
      "admin" ->
        conn

      _ ->
        conn
        |> put_flash(:error, "You can't access that page!")
        |> redirect(to: "/")
        |> halt
    end
  end

  def ensure_concierge(conn, _params) do
    case conn.assigns.current_user.role do
      "admin" ->
        conn

      "concierge" ->
        conn

      _ ->
        conn
        |> put_flash(:error, "You can't access that page!")
        |> redirect(to: "/access_denied")
        |> halt
    end
  end
end

apps/ticket_agent_web/lib/ticket_agent_web/controllers/admin/order_controller.ex
defmodule TicketAgentWeb.Admin.OrderController do
  use TicketAgentWeb, :controller
  alias TicketAgent.{Repo, Order}
  import Ecto.Query
  alias TicketAgent.State.ChargeProcessingState

  plug(TicketAgentWeb.Plugs.MenuLoader, %{root: "orders"})
  plug(TicketAgentWeb.Plugs.DatatablesParamParser)

  def index(conn, %{"_format" => "json"} = params) do
    records = retrieve_records(conn)

    render(
      conn,
      "index.json",
      records: records,
      page_number: conn.assigns.page_number,
      draw_number: conn.assigns.draw_number
    )
  end

  defp retrieve_records(
         %Plug.Conn{
           assigns: %{
             page_size: page_size,
             page_number: page_number,
             search_term: search_term,
             sort_column: sort_column,
             sort_dir: sort_dir
           }
         } = conn
       ) do
    query =
      from(
        l in Order,
        preload: [:user, :credit_card, :listing, :tickets],
        select: l
      )

    Repo.paginate(query, page: page_number, page_size: page_size)
  end

  def index(conn, params) do
    conn
    |> render("index.html")
  end

  def show(conn, %{"id" => id}) do
    order = Order.get_by_slug!(id)

    conn
    |> assign(:order, order)
    |> render("show.html")
  end

  def edit(conn, %{"id" => id}) do
    order = Order.get_by_slug!(id)
    changeset = Order.changeset(order, %{})

    conn
    |> assign(:order, order)
    |> assign(:changeset, changeset)
    |> render("edit.html")
  end

  def update(conn, %{"id" => id, "teacher" => teacher_params}) do
    teacher = Repo.get!(Order, id)
    changeset = Order.changeset(teacher, teacher_params)

    case Repo.update(changeset) do
      {:ok, teacher} ->
        conn
        |> put_flash(:info, "Order updated successfully.")
        |> redirect(to: admin_teacher_path(conn, :show, teacher))

      {:error, changeset} ->
        conn
        |> assign(:teacher, teacher)
        |> assign(:changeset, changeset)
        |> render("edit.html")
    end
  end

  def delete(conn, %{"id" => slug}) do
    remote_ip = conn.remote_ip |> Tuple.to_list() |> Enum.join(".")

    user = Coherence.current_user(conn)

    with order = Order.get_by_slug!(slug),
         "completed" <- order.status,
         {:ok, response} <- TicketAgent.Services.Stripe.refund(order, remote_ip),
         {:ok, %{order: updated_order, tickets: updated_tickets}} <-
           ChargeProcessingState.cancel_order_and_tickets(order, user.id) do
      IO.inspect("HAPP")
    else
      err ->
        IO.inspect("ERROR")
        IO.inspect(err)
    end

    # Repo.delete!(teacher)

    conn
    |> json("ok")
  end
end

apps/ticket_agent_web/lib/ticket_agent_web/controllers/backend/order_controller.ex
defmodule TicketAgentWeb.Backend.OrderController do
  use TicketAgentWeb, :controller
  alias TicketAgent.{Repo, Order}
  plug(TicketAgentWeb.Plugs.MenuLoader, %{root: "orders"})

  def index(conn, params) do
    orders = Order.list_orders(params)

    conn
    |> assign(:orders, orders)
    |> render("index.html")
  end

  def new(conn, _params) do
    changeset = Order.changeset(%Order{}, %{})

    conn
    |> assign(:changeset, changeset)
    |> render("new.html")
  end

  def create(conn, %{"teacher" => teacher_params}) do
    changeset = Order.changeset(%Order{}, teacher_params)

    case Repo.insert(changeset) do
      {:ok, teacher} ->
        conn
        |> put_flash(:info, "Order created successfully.")
        |> redirect(to: admin_teacher_path(conn, :show, teacher))

      {:error, changeset} ->
        conn
        |> assign(:changeset, changeset)
        |> render("new.html")
    end
  end

  def show(conn, %{"id" => id}) do
    order = Order.get_by_slug!(id)

    conn
    |> assign(:order, order)
    |> render("show.html")
  end

  def edit(conn, %{"id" => id}) do
    order = Order.get_by_slug!(id)
    changeset = Order.changeset(order, %{})

    conn
    |> assign(:order, order)
    |> assign(:changeset, changeset)
    |> render("edit.html")
  end

  def update(conn, %{"id" => id, "teacher" => teacher_params}) do
    teacher = Repo.get!(Order, id)
    changeset = Order.changeset(teacher, teacher_params)

    case Repo.update(changeset) do
      {:ok, teacher} ->
        conn
        |> put_flash(:info, "Order updated successfully.")
        |> redirect(to: admin_teacher_path(conn, :show, teacher))

      {:error, changeset} ->
        conn
        |> assign(:teacher, teacher)
        |> assign(:changeset, changeset)
        |> render("edit.html")
    end
  end

  def delete(conn, %{"id" => id}) do
    teacher = Repo.get!(Order, id)

    Repo.delete!(teacher)

    conn
    |> put_flash(:info, "Order deleted successfully.")
    |> redirect(to: admin_teacher_path(conn, :index))
  end
end

apps/ticket_agent_web/lib/ticket_agent_web/controllers/order_controller.ex
defmodule TicketAgentWeb.OrderController do
  require Logger
  use TicketAgentWeb, :controller
  alias TicketAgent.{Listing, Repo}
  alias TicketAgent.State.{OrderState, TicketState}
  alias TicketAgent.Finders.OrderFinder
  plug(TicketAgentWeb.Plugs.TicketInfoLoader when action in [:new])
  plug(TicketAgentWeb.Plugs.ValidateShowRequest when action in [:new])
  plug(TicketAgentWeb.Plugs.LoadListingWithRedirect when action in [:new])

  @host Application.get_env(:ticket_agent, :email_base_url, "https://pushcomedytheater.com")

  def index(conn, _) do
    conn
    |> redirect(to: dashboard_path(conn, :index))
  end

  def show(conn, %{"id" => order_id} = params) do
    current_user = Coherence.current_user(conn)

    order =
      order_id
      |> OrderFinder.find_order(current_user.id)
      |> Repo.preload([:credit_card, :tickets, :listing])

    if order do
      conn =
        case params["msg"] do
          nil ->
            conn

          _ ->
            conn
            |> put_flash(
              :info,
              "Thank you so much for your order.  You can find details about your order below.  Please check your email to receive your tickets."
            )
        end

      conn
      |> render("show.html", order: order, host: @host)
    else
      conn
      |> put_status(404)
      |> render(TicketAgentWeb.ErrorView, :"404", message: "Cannot find that order.")
      |> halt()
    end
  end

  def new(conn, params) do
    message =
      "Please verify that your order is correct.  Then enter your credit card number or use your browser to pay below."

    conn
    |> assign(:message, message)
    |> render("new.html")
  end

  def create(conn, %{"listing" => %{"id" => listing_id}} = params) do
    listing = Listing.get_listing!(listing_id)

    order =
      conn
      |> Coherence.current_user()
      |> OrderFinder.find_or_create_order()

    tickets_stored =
      params["tickets"]
      |> Enum.map(fn {group, tickets} ->
        Logger.info("Processing group #{group}")
        TicketState.reserve_tickets(order, tickets, group)
      end)
      |> Enum.find(fn response -> response != :ok end)
      |> is_nil

    if tickets_stored do
      Logger.info("All tickets were stored")

      {order, tickets, locked_until, pricing} =
        order
        |> Repo.reload()
        |> TicketState.load_minimum_locked_until(listing_id)
        |> OrderState.calculate_price()

      conn
      |> put_status(200)
      |> render(
        "create.json",
        %{
          order: order,
          tickets: tickets,
          locked_until: locked_until,
          pricing: pricing,
          pass_fees: listing.pass_fees_to_buyer
        }
      )
    else
      conn
      |> put_status(500)
      |> render(
        "create.json",
        %{}
      )
    end
  end

  def delete(conn, _) do
    case OrderFinder.find_started_order(Coherence.current_user(conn)) do
      nil ->
        Logger.warn("Not able to find this order")

      order ->
        maybe_release_tickets(order)
    end

    conn
    |> render("delete.json", %{})
  end

  defp maybe_release_tickets(order) do
    order
    |> TicketState.release_tickets()
    |> Ecto.Multi.append(OrderState.release_order(order))
    |> Repo.transaction()
  end
end

apps/ticket_agent_web/lib/ticket_agent_web/views/admin/order_view.ex
defmodule TicketAgentWeb.Admin.OrderView do
  use TicketAgentWeb, :view
  import Ecto.Query
  import Scrivener.HTML
  alias TicketAgent.Listing

  def render("index.json", %{records: records, page_number: page_number, draw_number: draw_number}) do
    %{
      recordsTotal: records.total_entries,
      draw: draw_number,
      recordsFiltered: records.total_entries,
      data: Enum.map(records, &records_json/1)
    }
  end

  def records_json(record) do
    %{
      id: record.id,
      slug: record.slug,
      buyer: record.user.name,
      listing: listing_name(record.listing),
      ticket_count: Enum.count(record.tickets),
      status: record.status,
      total: cost(record.total_price / 100),
      date: order_timestamp(record.completed_at)
    }
  end

  def order_status(status) do
    status
  end

  def listing_name(nil), do: ""

  def listing_name(listing) do
    listing.title
  end
end

apps/ticket_agent_web/lib/ticket_agent_web/views/backend/order_view.ex
defmodule TicketAgentWeb.Backend.OrderView do
  use TicketAgentWeb, :view
  import Scrivener.HTML

  def order_status(status) do
    status
  end
end

apps/ticket_agent_web/lib/ticket_agent_web/views/order_view.ex
defmodule TicketAgentWeb.OrderView do
  use TicketAgentWeb, :view

  def render("create.json", %{
        order: order,
        tickets: tickets,
        locked_until: locked_until,
        pricing: pricing,
        pass_fees: pass_fees
      }) do
    %{
      order_slug: order.slug,
      status: order.status,
      locked_until: locked_until,
      tickets: render_many(tickets, TicketAgentWeb.TicketView, "show.json"),
      pricing: pricing,
      pass_fees: pass_fees
    }
  end

  def render("delete.json", %{}) do
    %{
      message: "ok"
    }
  end
end

apps/ticket_agent_web/lib/ticket_agent_web/templates/order/new.html.eex
<%= render TicketAgentWeb.LayoutView, "ticket_info.html", assigns %>
<%= render "partial/order_template.html", assigns %>

<!-- Demo modal window -->
<div id="modal-type-aftersometime" class="js-autonomous-popup text-left g-max-width-600 g-bg-white g-overflow-y-auto g-pa-20" style="display: none;" data-modal-type="aftersometime" data-open-effect="zoomIn" data-close-effect="zoomOut" data-delay="100" data-speed="500">
  <h4 class="g-mb-20">Preparing Your Order</h4>
  <hr>
  <div class="progress g-height-20 rounded-0 u-progress g-mb-20">
    <div id="ticket_bar" class="progress-bar" role="progressbar" style="width: 20%" aria-valuenow="33" aria-valuemin="0" aria-valuemax="100" data-percentage="0"></div>
  </div>
  <p>We are validating and reserving your tickets and registration.</p>
</div>
<section class="g-bg-white">
  <div class="container">
    <div class="row" align="center">
    <div id="ticket_countdown" class="col-md-12 alert alert-warning block" role="alert" align="center">
      Your tickets will be released if you do not complete your order in the next: <strong id="locked_until"></strong>
    </div>

    </div>
    <div class="row">
      <div id="ticket_table" class="table-responsive col-md-6">
        <table class="table table-bordered table-hover u-table--v2 text-center text-uppercase g-col-border-side-0">
          <thead>
            <tr class="g-bg-blue g-color-white g-col-border-top-0">
              <th class="g-brd-white-opacity-0_1">Ticket</th>
              <th class="g-brd-white-opacity-0_1">Cost</th>
            </tr>
          </thead>
          <tbody class="g-font-size-12 g-color-black-opacity-0_6 g-font-weight-600" id="ticket_body">
          </tbody>
        </table>
      </div>
      <div class="col-md-6" id="charge_form">
        <form action="/charge" method="post" id="payment-form" class="g-brd-around g-brd-gray-light-v4 g-pa-30 g-mb-30">
          <div class="form-group row g-mb-25">
            <div id="payment-request-button" class="col-sm-12">
            </div>
          </div>
          <div class="d-flex justify-content-center text-center g-mb-30">
            <div class="d-inline-block align-self-center g-width-50 g-height-1 g-bg-gray-light-v1"></div>
            <span class="align-self-center g-color-gray-dark-v5 mx-4">OR ENTER CREDIT CARD DETAILS</span>
            <div class="d-inline-block align-self-center g-width-50 g-height-1 g-bg-gray-light-v1"></div>
          </div>
          <fieldset>
          <div class="form-group row g-mb-25">
            <label for="card-element" class="col-sm-4 col-form-label">Card Number</label>
            <div id="card-number" class="form-control col-md-6 g-color-black g-bg-white g-bg-white--focus g-brd-gray-light-v4 g-brd-primary--hover rounded g-py-15 g-px-15 card_class">
            </div>

          </div>
          <div class="form-group row g-mb-25">
            <label for="card-element" class="col-sm-4 col-form-label">Expiration Date</label>
            <div id="card-expiry" class="form-control col-md-6 g-color-black g-bg-white g-bg-white--focus g-brd-gray-light-v4 g-brd-primary--hover rounded g-py-15 g-px-15 card_class">
            </div>
          </div>
          <div class="form-group row g-mb-25">
            <label for="card-element" class="col-sm-4 col-form-label">CVV Code</label>
            <div id="card-cvc" class="form-control col-md-3 g-color-black g-bg-white g-bg-white--focus g-brd-gray-light-v4 g-brd-primary--hover rounded g-py-15 g-px-15 card_class">
            </div>
          </div>
          <div class="form-group row g-mb-25">
            <label for="card-element" class="col-sm-4 col-form-label">Zip Code</label>
            <input type="text" id="card_zip" name="card_zip" class="form-control col-md-3 g-color-black g-bg-white g-bg-white--focus g-brd-gray-light-v4 g-brd-primary--hover rounded g-py-15 g-px-15" placeholder="12345">
          </div>
          </fieldset>
          <div class="form-group row align-self-center" align="center">
            <div class="ml-sm-auto col-lg-12 align-self-center">
              <button id="submit_button" type="submit" class="btn btn-xxl u-btn-primary rounded-0">Loading....</button>
              <br />
              <br />
              <button id="cancel_button" class="btn btn-sm u-btn-bluegray rounded-0">Cancel Order</button>
              <br />
              <br />
              <div id="card_error" class="alert alert-danger" role="alert" style="display: none;">
                <strong>Oh snap!</strong> Change a few things up and try submitting again.
              </div>
            </div>
          </div>
        </form>

      </div>
      <div class="col-md-12" id="free_form" style="align: center; display: none;">
        <center>
          <button id="free_button" type="submit" class="btn btn-xxl u-btn-primary rounded-0">Reserve Tickets</button>
        </center>
        <br />
        <br />
      </div>
    </div>
  </div>
</section>
<script type="text/javascript">
  var tickets = {
  <%= for {p, ticket} <- @conn.assigns.tickets do %>
    "<%= p %>": <%= raw Jason.encode!(ticket) %>,
  <% end %>
  };

  window.details = {
    listing: {
      id: "<%= @listing.id %>",
      slug: "<%= @listing.slug %>",
      type: "<%= @listing.type %>",
      class_slug: "<%= class_slug(@listing.class_id) %>"
    },
    locked_until: null,
    order_id: null,
    pricing: {},
    tickets: tickets
  }

  window.csrf_token = $('meta[name="csrf-token"]').attr('content');
  $(document).on('ready', function () {
    var modal = new Custombox.modal({
      content: {
        effect: 'fadein',
        target: '#modal-type-aftersometime'
      }
    });
    modal.open();
  });
</script>
<script type="text/javascript" src="/js/stripe_related.js"></script>
<script src="https://cdn.rawgit.com/hilios/jQuery.countdown/master/dist/jquery.countdown.min.js"></script>

apps/ticket_agent_web/lib/ticket_agent_web/templates/order/show.html.eex
<br />
<br />
<br />
<br />
  <section class="g-bg-gray-light-v5 g-py-20">
    <div class="container">
      <div class="d-sm-flex text-center">

        <div class="align-self-center ml-auto">
          <ul class="u-list-inline">
            <li class="list-inline-item g-mr-5">
              <%= link "Home", to: root_path(@conn, :index), class: "u-link-v5 g-color-main g-color-primary--hover" %>
              <i class="g-color-gray-light-v2 g-ml-5">/</i>
            </li>
            <li class="list-inline-item g-mr-5">
              <%= link "Your Orders", to: dashboard_path(@conn, :index), class: "u-link-v5 g-color-main g-color-primary--hover" %>
              <i class="g-color-gray-light-v2 g-ml-5">/</i>
            </li>
            <li class="list-inline-item g-color-primary">
              <span>Order Details</span>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </section>
      <!-- End Breadcrumb -->
  <section class="g-py-20">

  <div class="container">
    <%= if get_flash(@conn, :info) do %>
     <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
   <% end %>
    <div class="pull-right">
    <%= raw credit_card_details(@order.credit_card) %><small>Ordered on <%= order_timestamp(@order.completed_at) %> | Order #<span class="text-uppercase"><%= @order.slug %></span></small></div>
    <h2>Order Details</h2>
    <table class="table" style="width: 100%;">
      <thead class="thead-default">
        <tr>
          <th colspan="2">
            Order Summary
          </th>
        </tr>
      </thead>
      <tr style="border-bottom: 1px solid #000; margin-bottom: 10px;">
        <th style="padding: 5px;">Item</th>
        <th style="padding: 5px;">Price</th>
      </tr>
      <%= for ticket <- @order.tickets do %>
        <tr>
          <td style="padding: 5px;"><%= ticket_details(ticket) %></td>
          <td style="padding: 5px;">$<%= :erlang.float_to_binary(ticket.price / 100,decimals: 2) %></td>
        </tr>
      <% end %>
      <tr>
        <td colspan="2">&nbsp;<br /></td>
      </tr>
      <% if @order.listing.pass_fees_to_buyer do %>
        <tr>
          <td style="padding: 5px; text-align: right;"><b>Subtotal:</b></td>
          <td style="padding: 5px;"><%= money(@order.subtotal) %></td>
        </tr>

        <tr>
          <td style="padding: 5px; text-align: right;"><b>Processing Fee:</b></td>
          <td style="padding: 5px;"><%= money(@order.total_price - @order.subtotal) %></td>
        </tr>
      <% end %>
      <tr>
        <td style="padding: 5px; text-align: right;"><b>Total:</b></td>
        <td style="padding: 5px;"><%= money(@order.total_price) %></td>
      </tr>
    </table>

    <%= link to: order_pdf_path(@conn, :show, @order.slug), class: "btn btn-lg u-btn-primary g-mr-10 g-mb-15" do %>
      <i class="fa fa-cloud-download g-mr-5"></i>Download Tickets
    <% end %>

  </div>
</section>