apps/ticket_agent_web/lib/ticket_agent_web/router.ex
defmodule TicketAgentWeb.Router do
  use TicketAgentWeb, :router
  # Add this
  use Coherence.Router

  pipeline :browser do
    plug(TicketAgentWeb.Plug.Timing)
    plug(:accepts, ["html", "ics"])
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
    # Add this
    plug(Coherence.Authentication.Session)
  end

  pipeline :webhook_browser do
    plug(:accepts, ["html"])
    plug(:put_secure_browser_headers)
  end

  pipeline :protected do
    plug(:accepts, ["html", "json"])
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
    # Add this
    plug(Coherence.Authentication.Session, protected: true)
  end

  pipeline :protected_api do
    plug(:accepts, ["json"])
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
    # Add this
    plug(Coherence.Authentication.Session, protected: true)
  end

  pipeline :admin_layout do
    plug(:put_layout, {TicketAgentWeb.Admin.LayoutView, :admin})
  end

  pipeline :backend_layout do
    plug(:put_layout, {TicketAgentWeb.Backend.LayoutView, :backend})
  end

  # Add this block
  scope "/" do
    pipe_through(:browser)
    coherence_routes()
  end

  # Add this block
  scope "/" do
    pipe_through(:protected)
    coherence_routes(:protected)
  end

  scope "/webhook", TicketAgentWeb do
    pipe_through(:webhook_browser)

    post("/:provider", WebhookController, :create)
  end

  scope "/", TicketAgentWeb do
    # Use the default browser stack
    pipe_through(:browser)
    resources("/about", AboutController, only: [:index, :show])
    resources("/camps", CampController, only: [:index, :show])
    resources("/charges", ChargeController, only: [:create])
    get("/event_calendar/:slug", EventCalendarController, :show, as: :event_ics)
    resources("/events", EventController, only: [:index, :show], param: "slug")
    get("/tickets/:listing_id/new", TicketController, :new, as: :new_ticket)
    resources("/tickets", TicketController)

    get("/ticket_auth/:token", TicketAuthController, :show, as: :ticket_auth)
    get("/ticket_auth", TicketAuthController, :new, as: :ticket_auth)
    post("/custom_registration", TicketAuthController, :create, as: :custom_registration)
    post("/waitlist", WaitlistController, :create, as: :waitlist)

    get("/workshops", WorkshopController, :index, as: :workshop)
    get("/classes", ClassController, :index, as: :classes)
    get("/classes/:type", ClassController, :class, as: :class_type)
    get("/class/:id", ClassController, :show, as: :class)

    get("/privacy", RootController, :privacy, as: :privacy)
    get("/terms", RootController, :terms, as: :terms)
    get("/", RootController, :index)
  end

  scope "/", TicketAgentWeb do
    pipe_through(:protected)
    resources("/orders", OrderController)
  end

  scope "/auth", TicketAgentWeb do
    pipe_through(:browser)

    get("/:provider", AuthController, :index)
    get("/:provider/callback", AuthController, :callback)
    delete("/logout", AuthController, :delete)
  end

  scope "/dashboard", TicketAgentWeb do
    pipe_through(:protected)
    get("/", DashboardController, :index)
    get("/tickets", Dashboard.TicketsController, :index, as: :dashboard_tickets)
    get("/classes", Dashboard.TicketsController, :index, as: :dashboard_classes)
    get("/order_pdf/:order_id", OrderPdfController, :show, as: :order_pdf)
  end

  scope "/concierge", TicketAgentWeb.Concierge do
    pipe_through([:protected, :ensure_concierge])
    get("/", DashboardController, :index, as: :concierge_dashboard)
    get("/single_checkin/:ticket_id", CheckinController, :show, as: :concierge_single_checkin)
    get("/listing_checkin/:listing_slug", CheckinController, :show, as: :concierge_checkin)
    resources("/checkin", CheckinController)
  end

  scope "/api", TicketAgentWeb.Api do
    pipe_through([:protected_api, :ensure_admin])
    get("/listings/:listing_slug/tickets", ListingTicketsController, :show)
  end

  scope "/admin", TicketAgentWeb.Admin do
    pipe_through([:protected, :ensure_admin, :admin_layout])
    get("/dashboard", DashboardController, :index, as: :admin_dashboard)
    get("/config", ConfigController, :index, as: :admin_config)

    resources("/classes", ClassController, as: :admin_class)
    resources("/listings", ListingController, as: :admin_event, param: "titled_slug")
    resources("/images", ImageController, as: :admin_image)
    resources("/orders", OrderController, as: :admin_order)
    resources("/teachers", TeacherController, as: :admin_teacher)
    resources("/tickets", TicketController, as: :admin_ticket)
    resources("/users", UserController, as: :admin_user)
    resources("/webhooks", WebHookController, as: :admin_webhook)

    get("/email_template/:type/:id", EmailTemplateController, :show, as: :admin_email_template)
    get("/email_template/:type", EmailTemplateController, :show, as: :admin_email_template)

    get("/", Redirect, to: "/admin/dashboard")
  end

  scope "/backend", TicketAgentWeb.Backend do
    pipe_through([:protected, :ensure_concierge, :backend_layout])
    get("/", DashboardController, :index, as: :backend_dashboard)
    resources("/classes", ClassController, as: :backend_class)
    resources("/listings", ListingController, as: :backend_event, param: "titled_slug")
    resources("/orders", OrderController, as: :backend_order)
    resources("/teachers", TeacherController, as: :backend_teacher)
    resources("/tickets", TicketController, as: :backend_ticket)
    resources("/users", UserController, as: :backend_user)
    resources("/webhooks", WebHookController, as: :backend_webhook)
  end

  def ensure_admin(conn, _params) do
    case conn.assigns.current_user.role do
      "admin" ->
        conn

      _ ->
        conn
        |> put_flash(:error, "You can't access that page!")
        |> redirect(to: "/")
        |> halt
    end
  end

  def ensure_concierge(conn, _params) do
    case conn.assigns.current_user.role do
      "admin" ->
        conn

      "concierge" ->
        conn

      _ ->
        conn
        |> put_flash(:error, "You can't access that page!")
        |> redirect(to: "/access_denied")
        |> halt
    end
  end
end

apps/ticket_agent_web/lib/ticket_agent_web/controllers/root_controller.ex
defmodule TicketAgentWeb.RootController do
  use TicketAgentWeb, :controller

  def index(conn, _params) do
    render(conn, "index.html")
  end

  def privacy(conn, _params) do
    render(conn, "privacy.html")
  end

  def terms(conn, _params) do
    render(conn, "terms.html")
  end
end

apps/ticket_agent_web/lib/ticket_agent_web/views/root_view.ex
defmodule TicketAgentWeb.RootView do
  alias TicketAgent.Random
  use TicketAgentWeb, :view

  @months ~w(Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec)
  @images ~w(push_sign push_sign push_sign push_sign push_sign push_sign driving
             lion lion lion lion lion elf_wizard alba_brad alba_brad alba_brad
             alba_brad ed_bunny life_preservers brad_purple brad_purple brad_purple
             brad_purple brad_purple brad_purple)

  def header_image do
    "https://pushcomedytheater.com/pushassets/images/headers/#{Random.sample(@images)}.jpg"
  end

  def event_date(date) do
    """
    <time datetime="#{date.year}-#{date.month}-#{date.day}">
      <span class="d-block g-color-black g-font-weight-700 g-font-size-40 g-line-height-1">
        #{date.day}
      </span> #{Enum.at(@months, date.month)}, #{date.year}
    </time>
    """
  end
end

apps/ticket_agent_web/lib/ticket_agent_web/templates/root/index.html.eex
<section class="g-bg-cover g-bg-pos-top-center g-bg-img-hero g-bg-black-opacity-0_3--after g-min-height-100vh g-flex-centered g-py-100" style="background-image: url(https://pushcomedytheater.com/pushassets/images/headers/provided_header.jpg);">
  <div class="container g-color-white text-center g-z-index-1">
    <div class="mb-5">
      <h2 class="g-font-weight-700 g-font-size-40 g-font-size-70--md text-uppercase g-mb-30">
        We are
        <span class="u-text-animation u-text-animation--typing"></span>
      </h2>
    </div>
    <%= link "Take A Class", to: classes_path(@conn, :index), class: "btn u-btn-outline-white g-color-white g-bg-white-opacity-0_1 g-color-black--hover g-bg-white--hover g-font-weight-600 text-uppercase g-rounded-50 g-px-30 g-py-13" %>
    &nbsp;
    <%= link "Watch A Show", to: event_path(@conn, :index), class: "btn u-btn-outline-white g-color-white g-bg-white-opacity-0_1 g-color-black--hover g-bg-white--hover g-font-weight-600 text-uppercase g-rounded-50 g-px-30 g-py-13" %>
    &nbsp;
    <%= link "Corporate Workshops", to: workshop_path(@conn, :index), class: "btn u-btn-outline-white g-color-white g-bg-white-opacity-0_1 g-color-black--hover g-bg-white--hover g-font-weight-600 text-uppercase g-rounded-50 g-px-30 g-py-13" %>
  </div>
</section>
<script>
  $(document).on('ready', function () {
      var typed = new Typed('.u-text-animation.u-text-animation--typing', {
        strings: ["improvisational", "funny", "musical", "dramatic"],
        typeSpeed: 60,
        loop: true,
        backDelay: 1500,
      });
    });
</script>
<!-- this is a comment ->

apps/ticket_agent_web/lib/ticket_agent_web/templates/root/privacy.html.eex
      <!-- Promo Block -->
      <section class="g-brd-bottom g-brd-gray-light-v4">
        <div class="container g-py-150">
          <div class="row">
            <div class="col-lg-6">
              <div class="d-inline-block g-width-80 g-height-2 g-bg-black mb-3"></div>
              <h2 class="g-color-black g-font-weight-700 g-font-size-50 g-line-height-1 mb-4">Privacy Policy</h2>
              <p class="mb-0">A privacy policy is a statement that discloses some or all of the ways a party gathers, uses, discloses, and manages a customer or client's data.</p><br />
              <p>Below is our privacy policy.</p>
            </div>
          </div>
        </div>
      </section>
      <!-- End Promo Block -->

      <section class="container g-py-100">
        <div class="g-mb-50">
          <h2 class="h3 g-color-black g-font-weight-600 mb-3">WHAT DO WE DO WITH YOUR INFORMATION?</h2>
          <div class="mb-4">
            <p><span class="g-font-weight-700">1.</span> When you purchase something from our store, as part of the buying and selling process, we collect the personal information you give us such as your name, address and email address.</p>
            <p><span class="g-font-weight-700">2.</span> When you browse our store, we also automatically receive your computer’s internet protocol (IP) address in order to provide us with information that helps us learn about your browser and operating system.</p>
            <p><span class="g-font-weight-700">3.</span> Email marketing (if applicable): With your permission, we may send you emails about our store, new products and other updates.</p>
          </div>
        </div>

        <div class="g-mb-50">
          <h3 class="g-color-black g-font-weight-600 mb-3">CONSENT</h3>
          <p><span class="g-font-weight-700">How do you get my consent?</span>&nbsp;When you provide us with personal information to complete a transaction, verify your credit card, place an order, arrange for a delivery or return a purchase, we imply that you consent to our collecting it and using it for that specific reason only.  If we ask for your personal information for a secondary reason, like marketing, we will either ask you directly for your expressed consent, or provide you with an opportunity to say no.</p>
          <p><span class="g-font-weight-700">How do I withdraw my consent?</span>&nbsp;If after you opt-in, you change your mind, you may withdraw your consent for us to contact you, for the continued collection, use or disclosure of your information, at anytime, by contacting us at support@pushcomedytheater.com or mailing us at: Push Comedy Theater 763 Granby Street, Norfolk, VA, 23510, United States.</p>
        </div>

        <div class="g-mb-50">
          <h3 class="g-color-black g-font-weight-600 mb-3">DISCLOSURE</h3>
          <p>We may disclose your personal information if we are required by law to do so or if you violate our Terms of Service.</p>
        </div>

        <div class="g-mb-50">
          <h3 class="g-color-black g-font-weight-600 mb-3">THIRD-PARTY SERVICES</h3>
          <p>In general, the third-party providers used by us will only collect, use and disclose your information to the extent necessary to allow them to perform the services they provide to us.</p>
          <p>However, certain third-party service providers, such as payment gateways and other payment transaction processors, have their own privacy policies in respect to the information we are required to provide to them for your purchase-related transactions.</p>
          <p>For these providers, we recommend that you read their privacy policies so you can understand the manner in which your personal information will be handled by these providers.</p>
          <p>In particular, remember that certain providers may be located in or have facilities that are located in a different jurisdiction than either you or us. So if you elect to proceed with a transaction that involves the services of a third-party service provider, then your information may become subject to the laws of the jurisdiction(s) in which that service provider or its facilities are located.</p>
          <p>As an example, if you are located in Canada and your transaction is processed by a payment gateway located in the United States, then your personal information used in completing that transaction may be subject to disclosure under United States legislation, including the Patriot Act.</p>
          <p>Once you leave our store’s website or are redirected to a third-party website or application, you are no longer governed by this Privacy Policy or our website’s Terms of Service.</p>
          <p>When you click on links on our store, they may direct you away from our site. We are not responsible for the privacy practices of other sites and encourage you to read their privacy statements.</p>
        </div>

        <div class="g-mb-50">
          <h3 class="g-color-black g-font-weight-600 mb-3">SECURITY</h3>
          <p>To protect your personal information, we take reasonable precautions and follow industry best practices to make sure it is not inappropriately lost, misused, accessed, disclosed, altered or destroyed.</p>
          <p>If you provide us with your credit card information, the information is encrypted using secure socket layer technology (SSL) and stored with a AES-256 encryption.  Although no method of transmission over the Internet or electronic storage is 100% secure, we follow all PCI-DSS requirements and implement additional generally accepted industry standards.</p>
        </div>

        <div class="g-mb-50">
          <h3 class="g-color-black g-font-weight-600 mb-3">AGE OF CONSENT</h3>
          <p>By using this site, you represent that you are at least the age of majority in your state or province of residence, or that you are the age of majority in your state or province of residence and you have given us your consent to allow any of your minor dependents to use this site.</p>
        </div>

        <div class="g-mb-50">
          <h3 class="g-color-black g-font-weight-600 mb-3">CHANGES TO THIS PRIVACY POLICY</h3>
          <p>We reserve the right to modify this privacy policy at any time, so please review it frequently. Changes and clarifications will take effect immediately upon their posting on the website. If we make material changes to this policy, we will notify you here that it has been updated, so that you are aware of what information we collect, how we use it, and under what circumstances, if any, we use and/or disclose it.</p>
          <p>If our company is acquired or merged with another company, your information may be transferred to the new owners so that we may continue to sell products to you.</p>
        </div>

        <div class="g-mb-50">
          <h3 class="g-color-black g-font-weight-600 mb-3">QUESTIONS AND CONTACT INFORMATION</h3>
          <p>If you would like to: access, correct, amend or delete any personal information we have about you, register a complaint, or simply want more information contact our Privacy Compliance Officer at support@pushcomedytheater.com or by mail at Push Comedy Theater, 763 Granby Street, Norfolk, VA, 23510, United States</p>
        </div>
      </section>