apps/ticket_agent_web/lib/ticket_agent_web/router.ex
defmodule TicketAgentWeb.Router do
  use TicketAgentWeb, :router
  # Add this
  use Coherence.Router

  pipeline :browser do
    plug(TicketAgentWeb.Plug.Timing)
    plug(:accepts, ["html", "ics"])
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
    # Add this
    plug(Coherence.Authentication.Session)
  end

  pipeline :webhook_browser do
    plug(:accepts, ["html"])
    plug(:put_secure_browser_headers)
  end

  pipeline :protected do
    plug(:accepts, ["html", "json"])
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
    # Add this
    plug(Coherence.Authentication.Session, protected: true)
  end

  pipeline :protected_api do
    plug(:accepts, ["json"])
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
    # Add this
    plug(Coherence.Authentication.Session, protected: true)
  end

  pipeline :admin_layout do
    plug(:put_layout, {TicketAgentWeb.Admin.LayoutView, :admin})
  end

  pipeline :backend_layout do
    plug(:put_layout, {TicketAgentWeb.Backend.LayoutView, :backend})
  end

  # Add this block
  scope "/" do
    pipe_through(:browser)
    coherence_routes()
  end

  # Add this block
  scope "/" do
    pipe_through(:protected)
    coherence_routes(:protected)
  end

  scope "/webhook", TicketAgentWeb do
    pipe_through(:webhook_browser)

    post("/:provider", WebhookController, :create)
  end

  scope "/", TicketAgentWeb do
    # Use the default browser stack
    pipe_through(:browser)
    resources("/about", AboutController, only: [:index, :show])
    resources("/camps", CampController, only: [:index, :show])
    resources("/charges", ChargeController, only: [:create])
    get("/event_calendar/:slug", EventCalendarController, :show, as: :event_ics)
    resources("/events", EventController, only: [:index, :show], param: "slug")
    get("/tickets/:listing_id/new", TicketController, :new, as: :new_ticket)
    resources("/tickets", TicketController)

    get("/ticket_auth/:token", TicketAuthController, :show, as: :ticket_auth)
    get("/ticket_auth", TicketAuthController, :new, as: :ticket_auth)
    post("/custom_registration", TicketAuthController, :create, as: :custom_registration)
    post("/waitlist", WaitlistController, :create, as: :waitlist)

    get("/workshops", WorkshopController, :index, as: :workshop)
    get("/classes", ClassController, :index, as: :classes)
    get("/classes/:type", ClassController, :class, as: :class_type)
    get("/class/:id", ClassController, :show, as: :class)

    get("/privacy", RootController, :privacy, as: :privacy)
    get("/terms", RootController, :terms, as: :terms)
    get("/", RootController, :index)
  end

  scope "/", TicketAgentWeb do
    pipe_through(:protected)
    resources("/orders", OrderController)
  end

  scope "/auth", TicketAgentWeb do
    pipe_through(:browser)

    get("/:provider", AuthController, :index)
    get("/:provider/callback", AuthController, :callback)
    delete("/logout", AuthController, :delete)
  end

  scope "/dashboard", TicketAgentWeb do
    pipe_through(:protected)
    get("/", DashboardController, :index)
    get("/tickets", Dashboard.TicketsController, :index, as: :dashboard_tickets)
    get("/classes", Dashboard.TicketsController, :index, as: :dashboard_classes)
    get("/order_pdf/:order_id", OrderPdfController, :show, as: :order_pdf)
  end

  scope "/concierge", TicketAgentWeb.Concierge do
    pipe_through([:protected, :ensure_concierge])
    get("/", DashboardController, :index, as: :concierge_dashboard)
    get("/single_checkin/:ticket_id", CheckinController, :show, as: :concierge_single_checkin)
    get("/listing_checkin/:listing_slug", CheckinController, :show, as: :concierge_checkin)
    resources("/checkin", CheckinController)
  end

  scope "/api", TicketAgentWeb.Api do
    pipe_through([:protected_api, :ensure_admin])
    get("/listings/:listing_slug/tickets", ListingTicketsController, :show)
  end

  scope "/admin", TicketAgentWeb.Admin do
    pipe_through([:protected, :ensure_admin, :admin_layout])
    get("/dashboard", DashboardController, :index, as: :admin_dashboard)
    get("/config", ConfigController, :index, as: :admin_config)

    resources("/classes", ClassController, as: :admin_class)
    resources("/listings", ListingController, as: :admin_event, param: "titled_slug")
    resources("/images", ImageController, as: :admin_image)
    resources("/orders", OrderController, as: :admin_order)
    resources("/teachers", TeacherController, as: :admin_teacher)
    resources("/tickets", TicketController, as: :admin_ticket)
    resources("/users", UserController, as: :admin_user)
    resources("/webhooks", WebHookController, as: :admin_webhook)

    get("/email_template/:type/:id", EmailTemplateController, :show, as: :admin_email_template)
    get("/email_template/:type", EmailTemplateController, :show, as: :admin_email_template)

    get("/", Redirect, to: "/admin/dashboard")
  end

  scope "/backend", TicketAgentWeb.Backend do
    pipe_through([:protected, :ensure_concierge, :backend_layout])
    get("/", DashboardController, :index, as: :backend_dashboard)
    resources("/classes", ClassController, as: :backend_class)
    resources("/listings", ListingController, as: :backend_event, param: "titled_slug")
    resources("/orders", OrderController, as: :backend_order)
    resources("/teachers", TeacherController, as: :backend_teacher)
    resources("/tickets", TicketController, as: :backend_ticket)
    resources("/users", UserController, as: :backend_user)
    resources("/webhooks", WebHookController, as: :backend_webhook)
  end

  def ensure_admin(conn, _params) do
    case conn.assigns.current_user.role do
      "admin" ->
        conn

      _ ->
        conn
        |> put_flash(:error, "You can't access that page!")
        |> redirect(to: "/")
        |> halt
    end
  end

  def ensure_concierge(conn, _params) do
    case conn.assigns.current_user.role do
      "admin" ->
        conn

      "concierge" ->
        conn

      _ ->
        conn
        |> put_flash(:error, "You can't access that page!")
        |> redirect(to: "/access_denied")
        |> halt
    end
  end
end

apps/ticket_agent_web/lib/ticket_agent_web/controllers/event_controller.ex
defmodule TicketAgentWeb.EventController do
  use TicketAgentWeb, :controller
  alias TicketAgent.Listing
  alias TicketAgent.Finders.{ShowFinder, WaitlistFinder}
  plug(TicketAgentWeb.Plugs.EventLoader when action in [:show])
  plug(TicketAgentWeb.Plugs.WaitlistLoader when action in [:show])

  def index(conn, _params) do
    conn
    |> assign(:page_title, "Upcoming Shows at Push Comedy Theater")
    |> render("index.html", events: ShowFinder.upcoming_listings())
  end

  def show(conn, %{"slug" => slug}) do
    conn
    |> render("show.html")
  end
end

apps/ticket_agent_web/lib/ticket_agent_web/views/event_view.ex
defmodule TicketAgentWeb.EventView do
  use TicketAgentWeb, :view
  alias TicketAgent.Finders.TicketFinder

  def load_event_image(event, width \\ 1050)

  def load_event_image(%{image_url: image_url}, width) do
    # from shared_view
    public_id = load_public_id(image_url)

    Cloudinex.Url.for(public_id, %{
      width: width,
      height: 400,
      gravity: "north",
      crop: "fill",
      flags: 'progressive'
    })
  end

  def load_event_image(_, _), do: ""

  def event_buy_timestamp(nil), do: ""

  def event_buy_timestamp(date) do
    date
    |> Calendar.DateTime.shift_zone!("America/New_York")
    |> Calendar.Strftime.strftime!("%m/%d/%Y at %l:%M%p")
  end

  def purchased_order_list(conn, orders) do
    Enum.map_join(orders, ", ", fn order ->
      safe_to_string(
        link(event_date(order.completed_at), to: order_path(conn, :show, order), target: "_blank")
      )
    end)
  end

  def aggregated_tags(shows) do
    Enum.reduce(shows, [], fn [show, _], acc ->
      tags = Enum.map(show.listing_tags, fn x -> x.tag end)
      acc ++ tags
    end)
    |> Enum.uniq()
    |> Enum.sort()
  end

  def show_tags(show) do
    show.listing_tags
    |> Enum.map(& &1.tag)
    |> Jason.encode!()
  end

  def event_cost(event) do
    range =
      event.listing_ids
      |> TicketFinder.price_range()
      |> cost_range

    case range do
      "FREE" -> "FREE"
      range -> "$#{range}"
    end
  end

  def listing_cost(listing) do
    ticket = Enum.at(listing.tickets, 0)

    (ticket.price / 100)
    |> :erlang.float_to_binary(decimals: 2)
  end

  def full_event_date(%{listing_count: listing_count}) when listing_count > 1 do
    "Multiple Dates"
  end

  def full_event_date(%{listing_count: listing_count, start_at: start_at})
      when listing_count == 1 do
    start_at
    |> Calendar.DateTime.shift_zone!("America/New_York")
    |> Calendar.Strftime.strftime!("%b %d, %Y - %l:%M%p")
  end

  def event_date_long(date) do
    date
    |> Calendar.DateTime.shift_zone!("America/New_York")
    |> Calendar.Strftime.strftime!("%b %d, %Y - %l:%M%p")
  end

  def listing_tags(show) do
    Enum.take(show.listing_tags, 5)
    |> Enum.map_join(", ", fn tag -> tag.tag end)
  end

  defp cost_range(%{min_price: nil, max_price: nil}), do: "FREE"
  defp cost_range(%{min_price: 0, max_price: 0}), do: "FREE"

  defp cost_range(%{min_price: min, max_price: max}) when max == min do
    (max / 100)
    |> :erlang.float_to_binary(decimals: 2)
  end

  defp cost_range(%{min_price: min, max_price: max}) do
    min =
      (min / 100)
      |> :erlang.float_to_binary(decimals: 2)

    max =
      (max / 100)
      |> :erlang.float_to_binary(decimals: 2)

    "#{min} - #{max}"
  end
end

apps/ticket_agent_web/lib/ticket_agent_web/views/shared_view.ex
defmodule TicketAgentWeb.SharedView do
  require Logger
  alias TicketAgent.{Class, Listing}

  def class_slug(nil), do: ""

  def class_slug(class_id) do
    class = Class.get_class!(class_id)
    class.slug
  end

  def current_class_listing(class), do: Listing.current_class_listing(class)

  def google_calendar(listing) do
    url = "http://www.google.com/calendar/render?action=TEMPLATE"

    url =
      url <>
        "&dates=#{calendar_timestamp(listing.start_at)}/#{calendar_timestamp(listing.end_at)}"

    url = url <> "&location=Push+Comedy+Theater,+763+Granby+St,+Norfolk,+VA+23510,+USA"
    url = url <> "&pli=1sf=true"
    url <> "&text=#{URI.encode(listing.title)}"
  end

  def calendar_timestamp(date) do
    date
    |> Calendar.Strftime.strftime!("%Y%m%dT%H%M%SZ")
  end

  def treeview_root(conn, path_combined) do
    treeview_root = Map.get(conn.assigns, :treeview_root, "unknown")

    cond do
      treeview_root == path_combined ->
        "active treeview menu-open"

      true ->
        "treeview"
    end
  end

  def treeview_action(conn, path_combined, existing \\ "") do
    treeview_action = Map.get(conn.assigns, :treeview_action, "unknown")
    # Logger.info "shared_view -> path_combined   = #{path_combined}"
    # Logger.info "shared_view -> treeview_action = #{treeview_action}"
    # Logger.info "shared_view -> existing        = #{existing}"
    [treeview_action_head, _] = String.split(treeview_action, "_")
    [path_combined_head, _] = String.split(path_combined, "_")

    cond do
      treeview_action == path_combined ->
        # Logger.info "shared_view -> match           = full"
        # Logger.info "-------"
        "#{existing} active"

      treeview_action_head == path_combined_head ->
        # Logger.info "shared_view -> match           = partial"
        # Logger.info "-------"
        "#{existing} active"

      true ->
        # Logger.info "shared_view -> match           = none"
        # Logger.info "-------"
        "#{existing}"
    end
  end

  def cc_icon("Visa"), do: "visa"
  def cc_icon("American Express"), do: "amex"
  def cc_icon("MasterCard"), do: "mastercard"
  def cc_icon("Discover"), do: "discover"
  def cc_icon("JCB"), do: "jcb"
  def cc_icon("Diners Club"), do: "diners-club"
  def cc_icon("Unknown"), do: "stripe"

  def credit_card_details(nil), do: ""

  def credit_card_details(card) do
    "<i class=\"fab fa-cc-#{cc_icon(card.type)}\"></i> #{card.type} ending in #{card.last_4}<br />"
  end

  def ticket_details(ticket) do
    cond do
      is_nil(ticket.guest_name) ->
        ticket.name

      String.length(ticket.guest_name) > 0 ->
        "#{ticket.name} (#{ticket.guest_name})"

      true ->
        ticket.name
    end
  end

  def event_date(nil), do: ""

  def event_date(date) do
    date
    |> Calendar.DateTime.shift_zone!("America/New_York")
    |> Calendar.Strftime.strftime!("%m/%d/%Y")
  end

  def event_time(nil), do: ""

  def event_time(date) do
    date
    |> Calendar.DateTime.shift_zone!("America/New_York")
    |> Calendar.Strftime.strftime!("%l:%M%p")
  end

  def order_timestamp(nil), do: ""

  def order_timestamp(date) do
    date
    |> Calendar.DateTime.shift_zone!("America/New_York")
    |> Calendar.Strftime.strftime!("%m/%d/%Y %l:%M%p")
  end

  def cost(ticket_price) when is_integer(ticket_price), do: cost(ticket_price / 1)

  def cost(ticket_price) when is_float(ticket_price) do
    ticket_price
    |> :erlang.float_to_binary(decimals: 2)
  end

  def money(price) do
    "$" <> :erlang.float_to_binary(price / 100, decimals: 2)
  end

  def cost_smallest_unit_with_dollar_sign(ticket_price) when ticket_price == 0, do: "FREE"

  def cost_smallest_unit_with_dollar_sign(ticket_price) do
    "$#{cost_smallest_unit(ticket_price)}"
  end

  def cost_smallest_unit(ticket_price) when is_integer(ticket_price),
    do: cost_smallest_unit(ticket_price / 1)

  def cost_smallest_unit(ticket_price) when is_float(ticket_price) do
    (ticket_price / 100)
    |> :erlang.float_to_binary(decimals: 2)
  end

  def formatted_ticket_price(price) do
    price
    |> :erlang.float_to_binary(decimals: 2)
  end

  def full_url(conn), do: "https://#{conn.host}#{conn.request_path}"

  def full_event_time(%{start_at: start_at, end_at: end_at}) when start_at != end_at do
    "#{event_time(start_at)} - #{event_time(end_at)}"
  end

  def full_event_time(%{start_at: start_at, end_at: end_at}) when start_at == end_at,
    do: event_time(start_at)

  def full_event_time(_), do: "Unknown"

  def listing_image_with_dimensions(show, width, height) do
    public_id = load_public_id(show.event.image_url)

    Cloudinex.Url.for(public_id, %{
      width: width,
      height: height,
      gravity: "north",
      crop: "fill",
      flags: 'progressive'
    })
  end

  def listing_image(show, width \\ 1050) do
    public_id = load_public_id(show.event.image_url)
    Logger.info("Listing image public id = #{public_id}")

    Cloudinex.Url.for(public_id, %{
      width: width,
      height: 400,
      gravity: "north",
      crop: "fill",
      flags: 'progressive'
    })
  end

  def event_image(image_url, width \\ 1050) do
    public_id = load_public_id(image_url)

    Logger.info("Event image is #{public_id}")

    Cloudinex.Url.for(public_id, %{
      width: width,
      height: 400,
      gravity: "north",
      crop: "fill",
      flags: 'progressive',
      format: "jpg",
      tag: "cover"
    })
  end

  def load_public_id(image_url) do
    public_id =
      image_url
      |> String.split("/")
      |> List.last()
      |> String.split(".")
      |> List.first()

    "covers/#{public_id}"
  end

  def open_graph_description(text, true) do
    HtmlSanitizeEx.strip_tags(text) |> truncated_description()
  end

  def open_graph_description(text, false) do
    HtmlSanitizeEx.strip_tags(text)
  end

  def page_description(conn) do
    default =
      "The Push Comedy Theater is a 90 seat venue in the heart of Norfolk's brand new Arts District."

    og_data(conn, :page_description, default)
  end

  def page_image(conn) do
    og_data(
      conn,
      :page_image,
      "https://pushcomedytheater.com/pushassets/images/logo.jpg"
    )
  end

  def page_title(conn), do: og_data(conn, :page_title, "Push Comedy Theater")

  def truncated_description(text, opts \\ []) do
    max_length = opts[:max_length] || 300
    omission = opts[:omission] || "..."

    cond do
      not String.valid?(text) ->
        text

      String.length(text) < max_length ->
        text

      true ->
        length_with_omission = max_length - String.length(omission)

        "#{String.slice(text, 0, length_with_omission)}#{omission}"
    end
  end

  defp og_data(conn, key, default) do
    case Map.get(conn.assigns, key) do
      nil -> default
      something -> something
    end
  end
end

apps/ticket_agent_web/lib/ticket_agent_web/templates/event/shared/_buy_multiple_tickets.html.eex
<button class="btn btn-block btn-xxl u-btn-inset u-btn-inset--rounded u-btn-primary u-btn-content g-font-weight-600 g-letter-spacing-0_5 text-uppercase g-mr-10 g-mb-15 g-brd-2 g-rounded-50 dropdown-toggle"  data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
  <i class="fa fa-ticket g-mr-3"></i>  Buy Tickets
  <div class="dropdown-menu" style="width: 100%;">
    <%= for listing <- @listings do %>
      <%= link to: ticket_path(@conn, :new, listing_id: listing), class: "dropdown-item" do %>
        <div class="listing-redirect" data-listing="<%= listing.slug %>" style="text-align: center; padding: 15px;"><%= event_buy_timestamp(listing.start_at) %></div>
      <% end %>
    <% end %>
  </div>    
</button>
<ins>This show has multiple performances, please choose your preferred time.</ins>
<script type="text/javascript">
$(document).on('ready', function () {
  $(".listing-redirect").on("click", function(e){
    var listing = $(this).data("listing");
    window.location.href = "<%= ticket_path(@conn, :new) %>?listing_id=" + listing;
  });
});
</script>

apps/ticket_agent_web/lib/ticket_agent_web/templates/event/shared/_buy_tickets.html.eex
<%= link to: ticket_path(@conn, :new, listing_id: @listing.slug), class: "btn btn-block btn-xxl u-btn-inset u-btn-inset--rounded u-btn-primary u-btn-content g-font-weight-600 g-letter-spacing-0_5 text-uppercase g-mr-10 g-mb-15 g-brd-2 g-rounded-50" do %>
  <i class="fa fa-ticket g-mr-3"></i>  Buy Tickets
  <span class="d-block g-font-size-14">for <%= order_timestamp(@listing.start_at) %></span>
<% end %>

apps/ticket_agent_web/lib/ticket_agent_web/templates/event/shared/_calendar_links.html.eex
        <h3 class="h5 g-color-black mb-3">Calendar (<%= order_timestamp(@listing.start_at) %>):</h3>
        <ul class="list-inline mb-0">
          <li class="list-inline-item mr-1">
            <a class="btn u-btn-outline-red g-rounded-25" href="<%= google_calendar(@listing) %>" target="_blank">
              <i class="mr-1 fab fa-google"></i>
              Add to Google Calendar
            </a>
          </li>
          <li class="list-inline-item mx-1">
            <a class="btn u-btn-outline-blue g-rounded-25" href="<%= event_ics_path(@conn, :show, @listing.slug) %>.ics" target="_blank">
              <i class="mr-1 fa fa-calendar"></i>
              ICal
            </a>
          </li>
        </ul>
        <br />

apps/ticket_agent_web/lib/ticket_agent_web/templates/event/shared/_ended.html.eex
<span class="btn-block btn-xxl u-btn-inset u-btn-inset--rounded u-btn-primary g-font-weight-600 g-letter-spacing-0_5 g-brd-2 g-rounded-50 g-mr-10 g-mb-15">
  <i class="fa fa-ticket g-mr-3"></i> No Shows
</span>

apps/ticket_agent_web/lib/ticket_agent_web/templates/event/shared/_listing_dates.html.eex
<%= if Enum.count(@listings) > 0 do %>
  <%= for listing <- @listings do %>
  <span class="u-label g-bg-orange u-label--med g-px-15 g-py-8 g-mr-10 g-mb-15">
    <i class="fa fa-calendar g-mr-3"></i> <%= order_timestamp(listing.start_at) %>
  </span>
  <% end %>   
<% else %>
  <span class="u-label g-bg-orange u-label--med g-px-15 g-py-8 g-mr-10 g-mb-15">
    <i class="fa fa-calendar g-mr-3"></i> No upcoming shows 
  </span>
<% end %>

apps/ticket_agent_web/lib/ticket_agent_web/templates/event/shared/_live.html.eex
<%= if Enum.count(@tickets) > 0 do %>
  <%= if Enum.count(@listings) > 1 do %>
    <%= render "shared/_buy_multiple_tickets.html", assigns %>
  <% else %>
    <%= render "shared/_buy_tickets.html", Map.put(assigns, :listing, Enum.at(@listings, 0)) %>
  <% end %>
<% else %>
  <%= render "shared/_sold_out.html", assigns %>
<% end %>

apps/ticket_agent_web/lib/ticket_agent_web/templates/event/shared/_previous_purchase.html.eex
<%= if @has_purchased_event do %>
  <p class="alert alert-info rounded" role="alert">
    You purchased tickets to this event on:  
    <%= raw purchased_order_list(@conn, @purchase_orders) %>
  </p>
<% end %>

apps/ticket_agent_web/lib/ticket_agent_web/templates/event/shared/_sharing.html.eex
      <!-- Share -->
      <div class="mb-4">
        <h3 class="h5 g-color-black mb-3">Share:</h3>
        <ul class="list-inline mb-0">
          <li class="list-inline-item mr-1">
            <a class="btn u-btn-outline-facebook g-rounded-25" href="https://www.facebook.com/sharer/sharer.php?u=<%= full_url(@conn) %>" target="_blank">
              <i class="mr-1 fab fa-facebook"></i>
              Facebook
            </a>
          </li>
          <li class="list-inline-item mx-1">
            <a class="btn u-btn-outline-twitter g-rounded-25" href="https://twitter.com/home?status=Check%20out%20this%20show%20at%20Push%20Comedy%20Theater%20<%= full_url(@conn) %>%20via%20%40pushcomedy" target="_blank">
              <i class="mr-1 fab fa-twitter"></i>
              Twitter
            </a>
          </li>
        </ul>
        <br />
        <%= if Enum.count(@listings) > 0 do %>
          <%= for listing <- @listings do %>
            <%= render "shared/_calendar_links.html", listing: listing, conn: @conn %>
          <% end %>
        <% end %>
      </div>
      <!-- End Share -->

apps/ticket_agent_web/lib/ticket_agent_web/templates/event/shared/_sold_out.html.eex
            <div class="alert alert-dismissible fade show g-bg-yellow rounded-0" role="alert">
              <div class="media">
                <span class="d-flex g-mr-10 g-mt-5">
                  <i class="icon-info g-font-size-25"></i>
                </span>
                <span class="media-body align-self-center">
                  This show has sold out.
                </span>
              </div>
            </div>

            <%= if false do %>
            <a style="margin-left: 20px;" href="#" onclick="return false;" class="btn btn-md u-btn-inset u-btn-inset--rounded u-btn-blue g-font-weight-600 g-letter-spacing-0_5 text-uppercase g-brd-2 g-rounded-50 g-mr-10 g-mb-15">
              <i class="fa fa-check-circle g-mr-3"></i>
              On Waitlist
            </a>
            <% else %>
              <a style="margin-left: 20px;" href="#waitlist" data-modal-target="#waitlist" data-modal-effect="slide" class="btn btn-md u-btn-inset u-btn-inset--rounded u-btn-blue g-font-weight-600 g-letter-spacing-0_5 text-uppercase g-brd-2 g-rounded-50 g-mr-10 g-mb-15">
                <i class="fa fa-check-circle g-mr-3"></i>
                Join Waitlist
              </a>
              <div id="waitlist" class="text-left g-max-width-600 g-bg-white g-overflow-y-auto g-pa-20" style="display: none;">
                <button type="button" class="close" onclick="Custombox.modal.close();">
                  <i class="hs-icon hs-icon-close"></i>
                </button>
                <h4 class="g-mb-20">Waitlist</h4>
                <p>This show is currently sold out.  We have no more tickets to sell online.</p>
                <p>However, you are welcome to join our waitlist and we will send you an email if any tickets become available.</p>
                <div class="form-group g-mb-20">
                  <div class="u-input-group-v2">
                    <input id="name" class="form-control rounded-0 u-form-control" name="full-name" type="text" value="<%= Coherence.current_user_name(@conn) %>">
                    <label for="name">Full Name</label>
                  </div>
                  <small id="name_required" class="form-control-feedback" style="color: red; display: none;">This is a required field.</small>
                </div>
                <div class="form-group g-mb-20">
                  <div class="u-input-group-v2">
                    <input id="email" class="form-control rounded-0 u-form-control" name="full-name" type="text" value="<%= Coherence.current_user_name(@conn, :email) %>">
                    <label for="email">Email Address</label>
                  </div>
                  <small id="email_required" class="form-control-feedback" style="color: red; display: none;">This is a required field.</small>
                </div>
                <a href="#!" id="add_waitlist_btn" class="btn btn-md u-btn-outline-primary g-mr-10 g-mb-15">Add Me To Waitlist</a>
              </div>
            <% end %>

apps/ticket_agent_web/lib/ticket_agent_web/templates/event/shared/_tags.html.eex
<ul class="u-list-inline mb-0">
  <%= for tag <- @event.event_tags do %>
  <li class="list-inline-item g-mb-10">
    <%= link to: event_path(@conn, :index, tag: tag.tag), class: "u-tags-v1 g-color-white g-brd-around g-brd-gray-light-v3 g-bg-gray-dark-v2--hover g-brd-gray-dark-v2--hover g-color-white--hover g-rounded-50 g-py-4 g-px-15" do %>
      <strong><%= tag.tag %></strong>
    <% end %>
  </li>
  <% end %>
</ul>

apps/ticket_agent_web/lib/ticket_agent_web/templates/event/shared/_ticket_price.html.eex
<%
min_ticket_price = if is_nil(assigns[:min_ticket_price]), do: 0, else: assigns[:min_ticket_price]
max_ticket_price = if is_nil(assigns[:max_ticket_price]), do: 0, else: assigns[:max_ticket_price]
%>
<span id="ticket_price" class="u-label g-rounded-20 g-bg-green g-px-15 g-mr-30 g-mb-15">
  <%= if min_ticket_price != max_ticket_price do %>
    <i class="fa fa-dollar g-mr-3"></i><strong><%= cost_smallest_unit_with_dollar_sign(min_ticket_price) %> - <%= cost_smallest_unit_with_dollar_sign(max_ticket_price) %></strong>
  <% else %>
    <i class="fa fa-dollar g-mr-3"></i><strong><%= cost_smallest_unit_with_dollar_sign(min_ticket_price) %></strong>
  <% end %>
</span>

apps/ticket_agent_web/lib/ticket_agent_web/templates/event/shared/tag_sidebar.html.eex
        <div class="col-lg-3 g-pr-40--lg g-mb-50 g-mb-0--lg">
          <!-- Tags -->
          <h2 class="h5 text-uppercase g-color-gray-dark-v1">Tags</h2>
          <hr class="g-brd-gray-light-v4 g-my-15">
          <ul id="aggregated_tags" class="list-inline g-mb-40">
            <%= for tag <- aggregated_tags(@shows) do %>
            <li class="list-inline-item my-2">
              <a data-selected="false" class="u-tags-v1 g-color-main g-brd-around g-brd-gray-light-v3 g-bg-gray-dark-v2--hover g-brd-gray-dark-v2--hover g-color-white--hover g-rounded-50 g-py-4 g-px-15 tagger" href="#"><%= tag %></a>
            </li>
            <% end %>
          </ul>
          <!-- End Tags -->
        </div>